spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.xuecheng.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
spring:
  profiles: dev
  application:
    name: microservicecloud-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3307/clouddb01?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8            # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200      # 等待连接获取的最大超时时间
  rabbitmq:
    host: 192.168.50.100
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        myInput:
          destination: minestream
          group: stream
          consumer:
            partitioned: true  #启动分区
        myOutput:
          destination: minestream
          producer:
            partitionKeyExpression: payload
            partitionCount: 1
      instance-count: 1
      instance-index: 0
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ejb:
          interceptor: com.xuecheng.userservice.component.QueryResInterceptor
        cache:
          use_second_level_cache: true
    hibernate:
      ddl-auto: update
  redis:
    host: 192.168.50.100
    port: 6379
  data:
    mongodb:
      uri: mongodb://192.168.50.100:27017/mydb
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
eureka:
  client:
    service-url:
      defaultZone: http://cxw1.com:7001/eureka,http://cxw2.com:7002/eureka
  instance: #实例别名
    instance-id: servuce-cloued8001XX
    prefer-ip-address: true